title: Benjamin Bellamy
baseurl: https://benjaminbellamy.fr/
description: Benjamin Bellamy's social media reference landing page
author:
  name: Benjamin Bellamy
  url: https://benjaminbellamy.fr
language: en
languages:
  - code: en
    locale: en_US
    name: English
  #- code: fr
  #  locale: fr
  #  name: Français
avatar: avatar.jpg
image: avatar.jpg # image used for the social share
metatags:
  favicon:
    image: avatar.jpg
source: https://github.com/benjaminbellamy/benjaminbellamy.fr
theme:
  - fontawesome
  - pwa
  #- netlify
manifest:
  background_color: '#2a2d7c'
  theme_color: '#e91e63'
serviceworker:
  enabled: true

assets:
  images:
    optimize:
      enabled: true
    responsive:
      enabled: true
    webp:
      enabled: true
taxonomies:
  categories: disabled
  tags: disabled
pagination:
  enabled: false
pages:
  default:
    404:
      published: false
    sitemap:
      published: false
    xsl/atom:
      published: false
    xsl/rss:
      published: false
output:
  pagetypeformats:
    homepage: html
